import React, { useState, useEffect } from 'react';
import { ShieldAlert, CheckCircle2, Search, Filter, Eye, AlertTriangle } from 'lucide-react';
import { api } from '../services/api';
import { SeverityBadge } from '../components/common/Badge';
import { useWebSocket } from '../context/WebSocketContext';

export const ActiveAlertsPage = () => {
  const [alerts, setAlerts] = useState([]);
  const [statusFilter, setStatusFilter] = useState('all');
  const [severityFilter, setSeverityFilter] = useState('all');
  const [selectedAlert, setSelectedAlert] = useState(null);
  const [resolutionNotes, setResolutionNotes] = useState('');
  const [loading, setLoading] = useState(true);

  const { liveAlerts } = useWebSocket();

  const loadAlerts = async () => {
    try {
      const params = {};
      if (statusFilter !== 'all') params.status = statusFilter;
      if (severityFilter !== 'all') params.severity = severityFilter;
      const data = await api.getAlerts(params);
      setAlerts(data);
    } catch (e) {
      console.warn("Could not load alerts:", e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadAlerts();
  }, [statusFilter, severityFilter]);

  // Merge live WebSocket alerts
  const allAlerts = [...liveAlerts, ...alerts];
  // Deduplicate by ID
  const uniqueAlerts = Array.from(new Map(allAlerts.map(item => [item.id || item.alert_id, item])).values());

  const filteredAlerts = uniqueAlerts.filter((a) => {
    if (statusFilter !== 'all' && a.status !== statusFilter) return false;
    if (severityFilter !== 'all' && a.severity !== severityFilter) return false;
    return true;
  });

  const handleAcknowledge = async (alertId) => {
    await api.acknowledgeAlert(alertId);
    setAlerts((prev) =>
      prev.map((a) => ((a.id || a.alert_id) === alertId ? { ...a, status: 'acknowledged' } : a))
    );
  };

  const handleResolve = async () => {
    if (!selectedAlert || !resolutionNotes) return;
    const alertId = selectedAlert.id || selectedAlert.alert_id;
    await api.resolveAlert(alertId, resolutionNotes);
    setAlerts((prev) =>
      prev.map((a) => ((a.id || a.alert_id) === alertId ? { ...a, status: 'resolved', resolution_notes: resolutionNotes } : a))
    );
    setSelectedAlert(null);
    setResolutionNotes('');
  };

  return (
    <div className="space-y-6">
      {/* Header & Filter Controls */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-bold text-slate-100 font-mono tracking-wide">
            OPERATIONAL ALERT TRIAGE
          </h1>
          <p className="text-xs text-slate-400 font-mono">
            Sub-second real-time security events generated by YOLOv8 + ByteTrack
          </p>
        </div>

        {/* Severity & Status Filter Tabs */}
        <div className="flex items-center gap-2 flex-wrap">
          <div className="flex items-center bg-slate-900 border border-slate-800 rounded-lg p-1 text-xs font-mono">
            {['all', 'new', 'acknowledged', 'resolved'].map((s) => (
              <button
                key={s}
                onClick={() => setStatusFilter(s)}
                className={`px-3 py-1 rounded uppercase ${
                  statusFilter === s ? 'bg-cyan-500/20 text-cyan-300 font-semibold' : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                {s}
              </button>
            ))}
          </div>

          <select
            value={severityFilter}
            onChange={(e) => setSeverityFilter(e.target.value)}
            className="px-3 py-1.5 bg-slate-900 border border-slate-800 rounded-lg text-xs font-mono text-slate-300 focus:outline-none focus:border-cyan-500"
          >
            <option value="all">ALL SEVERITIES</option>
            <option value="critical">CRITICAL</option>
            <option value="high">HIGH</option>
            <option value="medium">MEDIUM</option>
          </select>
        </div>
      </div>

      {/* Alerts Table */}
      <div className="bg-slate-900/80 border border-slate-800 rounded-xl overflow-hidden shadow-xl">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs font-mono">
            <thead className="bg-slate-950/80 text-slate-400 uppercase border-b border-slate-800">
              <tr>
                <th className="p-4">Severity</th>
                <th className="p-4">Time (UTC)</th>
                <th className="p-4">Sector / Camera</th>
                <th className="p-4">Incident Event Summary</th>
                <th className="p-4">Status</th>
                <th className="p-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/80 text-slate-300">
              {filteredAlerts.length === 0 ? (
                <tr>
                  <td colSpan="6" className="p-8 text-center text-slate-500">
                    No alerts matching current filter conditions.
                  </td>
                </tr>
              ) : (
                filteredAlerts.map((a) => {
                  const alertId = a.id || a.alert_id;
                  const isNew = a.status === 'new';
                  return (
                    <tr
                      key={alertId}
                      className={`hover:bg-slate-800/40 transition-colors ${
                        isNew ? 'bg-red-500/5' : ''
                      }`}
                    >
                      <td className="p-4 whitespace-nowrap">
                        <SeverityBadge severity={a.severity} />
                      </td>
                      <td className="p-4 whitespace-nowrap text-slate-400">
                        {new Date(a.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })}
                      </td>
                      <td className="p-4 whitespace-nowrap text-slate-200 font-semibold">
                        {a.camera_name || 'Watchtower 04'}
                      </td>
                      <td className="p-4 max-w-md">
                        <div className="font-semibold text-slate-100 font-sans text-xs">{a.title}</div>
                        <div className="text-[11px] text-slate-400 font-sans truncate">{a.description}</div>
                      </td>
                      <td className="p-4 whitespace-nowrap">
                        <span className={`px-2 py-0.5 rounded text-[11px] font-mono uppercase ${
                          a.status === 'new'
                            ? 'bg-red-500/20 text-red-400 border border-red-500/40'
                            : a.status === 'acknowledged'
                            ? 'bg-amber-500/20 text-amber-400 border border-amber-500/40'
                            : 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/40'
                        }`}>
                          {a.status}
                        </span>
                      </td>
                      <td className="p-4 whitespace-nowrap text-right space-x-2">
                        <button
                          onClick={() => setSelectedAlert(a)}
                          className="px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700 transition-colors"
                        >
                          Evidence
                        </button>
                        {isNew && (
                          <button
                            onClick={() => handleAcknowledge(alertId)}
                            className="px-2.5 py-1 rounded bg-red-600 hover:bg-red-500 text-white font-semibold transition-colors"
                          >
                            Acknowledge
                          </button>
                        )}
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Forensic Evidence & Resolution Modal */}
      {selectedAlert && (
        <div className="fixed inset-0 z-50 bg-black/75 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-slate-900 border border-slate-800 rounded-2xl max-w-2xl w-full p-6 space-y-5 shadow-2xl">
            <div className="flex items-center justify-between pb-3 border-b border-slate-800">
              <div className="flex items-center gap-2">
                <SeverityBadge severity={selectedAlert.severity} />
                <h3 className="font-semibold text-slate-100">{selectedAlert.title}</h3>
              </div>
              <button
                onClick={() => setSelectedAlert(null)}
                className="text-slate-500 hover:text-slate-300 font-mono"
              >
                ✕
              </button>
            </div>

            {/* Evidence Image Preview */}
            <div className="relative rounded-xl overflow-hidden border border-slate-800 bg-black aspect-video flex items-center justify-center">
              <img
                src={selectedAlert.thumbnail_url || "/static/evidence/snapshots/sample_evidence_104.jpg"}
                alt="Forensic Snapshot"
                className="w-full h-full object-contain"
                onError={(e) => {
                  e.target.style.display = 'none';
                }}
              />
              <div className="absolute bottom-2 left-2 px-2.5 py-1 rounded bg-black/80 text-[10px] font-mono text-cyan-400 border border-slate-800">
                SHA-256: a1b2c3d4e5f6... (IMMUTABLE AUDIT TRAIL)
              </div>
            </div>

            <div className="text-xs text-slate-300 space-y-1 font-mono">
              <div>Camera: <span className="text-slate-100">{selectedAlert.camera_name || 'Watchtower 04'}</span></div>
              <div>Timestamp: <span className="text-slate-100">{selectedAlert.created_at}</span></div>
              <div>Details: <span className="text-slate-400 font-sans">{selectedAlert.description}</span></div>
              {selectedAlert.resolution_notes && (
                <div className="p-2 rounded bg-slate-950 border border-slate-800 text-emerald-400">
                  Resolution Log: {selectedAlert.resolution_notes}
                </div>
              )}
            </div>

            {selectedAlert.status !== 'resolved' && (
              <div className="space-y-3 pt-3 border-t border-slate-800">
                <label className="block text-xs font-mono text-slate-300">
                  Officer Incident Resolution Remarks
                </label>
                <textarea
                  rows="2"
                  value={resolutionNotes}
                  onChange={(e) => setResolutionNotes(e.target.value)}
                  placeholder="e.g. Quick Reaction Team dispatched. False alarm triggered by stray wildlife. Sector clear."
                  className="w-full p-2 text-xs bg-slate-950 border border-slate-700 rounded-lg text-slate-100 font-sans focus:outline-none focus:border-cyan-500"
                />

                <div className="flex justify-end gap-2">
                  <button
                    onClick={() => setSelectedAlert(null)}
                    className="px-3 py-1.5 rounded text-xs font-mono text-slate-400 hover:text-slate-200"
                  >
                    Close
                  </button>
                  <button
                    onClick={handleResolve}
                    disabled={!resolutionNotes.trim()}
                    className="px-4 py-1.5 rounded text-xs font-mono font-semibold bg-emerald-600 hover:bg-emerald-500 disabled:opacity-50 text-white transition-colors"
                  >
                    Resolve & Close Incident
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};
