/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CameraHealthRouteImport } from './routes/camera-health'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as FencesRouteImport } from './routes/fences'
import { Route as InvestigationRouteImport } from './routes/investigation'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminCamerasRouteImport } from './routes/admin/cameras'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminZonesRouteImport } from './routes/admin/zones'
import { Route as DetectionsAnprRouteImport } from './routes/detections/anpr'
import { Route as DetectionsFaceRouteImport } from './routes/detections/face'
import { Route as DetectionsHumanRouteImport } from './routes/detections/human'
import { Route as DetectionsVehicleRouteImport } from './routes/detections/vehicle'
import { Route as IncidentsIndexRouteImport } from './routes/incidents/index'
import { Route as IncidentsIdRouteImport } from './routes/incidents/$id'
import { Route as SurveillanceIndexRouteImport } from './routes/surveillance/index'
import { Route as SurveillancePriorityRouteImport } from './routes/surveillance/priority'
import { Route as TrackingJourneyRouteImport } from './routes/tracking/journey'
import { Route as TrackingPersonRouteImport } from './routes/tracking/person'
import { Route as TrackingVehicleRouteImport } from './routes/tracking/vehicle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraHealthRoute = CameraHealthRouteImport.update({
  id: '/camera-health',
  path: '/camera-health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const FencesRoute = FencesRouteImport.update({
  id: '/fences',
  path: '/fences',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationRoute = InvestigationRouteImport.update({
  id: '/investigation',
  path: '/investigation',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCamerasRoute = AdminCamerasRouteImport.update({
  id: '/admin/cameras',
  path: '/admin/cameras',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminZonesRoute = AdminZonesRouteImport.update({
  id: '/admin/zones',
  path: '/admin/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionsAnprRoute = DetectionsAnprRouteImport.update({
  id: '/detections/anpr',
  path: '/detections/anpr',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionsFaceRoute = DetectionsFaceRouteImport.update({
  id: '/detections/face',
  path: '/detections/face',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionsHumanRoute = DetectionsHumanRouteImport.update({
  id: '/detections/human',
  path: '/detections/human',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionsVehicleRoute = DetectionsVehicleRouteImport.update({
  id: '/detections/vehicle',
  path: '/detections/vehicle',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIndexRoute = IncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIdRoute = IncidentsIdRouteImport.update({
  id: '/incidents/$id',
  path: '/incidents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveillanceIndexRoute = SurveillanceIndexRouteImport.update({
  id: '/surveillance/',
  path: '/surveillance/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveillancePriorityRoute = SurveillancePriorityRouteImport.update({
  id: '/surveillance/priority',
  path: '/surveillance/priority',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingJourneyRoute = TrackingJourneyRouteImport.update({
  id: '/tracking/journey',
  path: '/tracking/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingPersonRoute = TrackingPersonRouteImport.update({
  id: '/tracking/person',
  path: '/tracking/person',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingVehicleRoute = TrackingVehicleRouteImport.update({
  id: '/tracking/vehicle',
  path: '/tracking/vehicle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/camera-health': typeof CameraHealthRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/fences': typeof FencesRoute
  '/investigation': typeof InvestigationRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/search': typeof SearchRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/cameras': typeof AdminCamerasRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/zones': typeof AdminZonesRoute
  '/detections/anpr': typeof DetectionsAnprRoute
  '/detections/face': typeof DetectionsFaceRoute
  '/detections/human': typeof DetectionsHumanRoute
  '/detections/vehicle': typeof DetectionsVehicleRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/surveillance/priority': typeof SurveillancePriorityRoute
  '/tracking/journey': typeof TrackingJourneyRoute
  '/tracking/person': typeof TrackingPersonRoute
  '/tracking/vehicle': typeof TrackingVehicleRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/surveillance/': typeof SurveillanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/camera-health': typeof CameraHealthRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/fences': typeof FencesRoute
  '/investigation': typeof InvestigationRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/search': typeof SearchRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/cameras': typeof AdminCamerasRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/zones': typeof AdminZonesRoute
  '/detections/anpr': typeof DetectionsAnprRoute
  '/detections/face': typeof DetectionsFaceRoute
  '/detections/human': typeof DetectionsHumanRoute
  '/detections/vehicle': typeof DetectionsVehicleRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/surveillance/priority': typeof SurveillancePriorityRoute
  '/tracking/journey': typeof TrackingJourneyRoute
  '/tracking/person': typeof TrackingPersonRoute
  '/tracking/vehicle': typeof TrackingVehicleRoute
  '/incidents': typeof IncidentsIndexRoute
  '/surveillance': typeof SurveillanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/camera-health': typeof CameraHealthRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/fences': typeof FencesRoute
  '/investigation': typeof InvestigationRoute
  '/journey': typeof JourneyRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/search': typeof SearchRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/cameras': typeof AdminCamerasRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/zones': typeof AdminZonesRoute
  '/detections/anpr': typeof DetectionsAnprRoute
  '/detections/face': typeof DetectionsFaceRoute
  '/detections/human': typeof DetectionsHumanRoute
  '/detections/vehicle': typeof DetectionsVehicleRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/surveillance/priority': typeof SurveillancePriorityRoute
  '/tracking/journey': typeof TrackingJourneyRoute
  '/tracking/person': typeof TrackingPersonRoute
  '/tracking/vehicle': typeof TrackingVehicleRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/surveillance/': typeof SurveillanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/camera-health'
    | '/dashboard'
    | '/evidence'
    | '/fences'
    | '/investigation'
    | '/journey'
    | '/login'
    | '/map'
    | '/reports'
    | '/risk'
    | '/search'
    | '/admin/audit-logs'
    | '/admin/cameras'
    | '/admin/users'
    | '/admin/zones'
    | '/detections/anpr'
    | '/detections/face'
    | '/detections/human'
    | '/detections/vehicle'
    | '/incidents/$id'
    | '/surveillance/priority'
    | '/tracking/journey'
    | '/tracking/person'
    | '/tracking/vehicle'
    | '/incidents/'
    | '/surveillance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/camera-health'
    | '/dashboard'
    | '/evidence'
    | '/fences'
    | '/investigation'
    | '/journey'
    | '/login'
    | '/map'
    | '/reports'
    | '/risk'
    | '/search'
    | '/admin/audit-logs'
    | '/admin/cameras'
    | '/admin/users'
    | '/admin/zones'
    | '/detections/anpr'
    | '/detections/face'
    | '/detections/human'
    | '/detections/vehicle'
    | '/incidents/$id'
    | '/surveillance/priority'
    | '/tracking/journey'
    | '/tracking/person'
    | '/tracking/vehicle'
    | '/incidents'
    | '/surveillance'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/camera-health'
    | '/dashboard'
    | '/evidence'
    | '/fences'
    | '/investigation'
    | '/journey'
    | '/login'
    | '/map'
    | '/reports'
    | '/risk'
    | '/search'
    | '/admin/audit-logs'
    | '/admin/cameras'
    | '/admin/users'
    | '/admin/zones'
    | '/detections/anpr'
    | '/detections/face'
    | '/detections/human'
    | '/detections/vehicle'
    | '/incidents/$id'
    | '/surveillance/priority'
    | '/tracking/journey'
    | '/tracking/person'
    | '/tracking/vehicle'
    | '/incidents/'
    | '/surveillance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CameraHealthRoute: typeof CameraHealthRoute
  DashboardRoute: typeof DashboardRoute
  EvidenceRoute: typeof EvidenceRoute
  FencesRoute: typeof FencesRoute
  InvestigationRoute: typeof InvestigationRoute
  JourneyRoute: typeof JourneyRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  ReportsRoute: typeof ReportsRoute
  RiskRoute: typeof RiskRoute
  SearchRoute: typeof SearchRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCamerasRoute: typeof AdminCamerasRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminZonesRoute: typeof AdminZonesRoute
  DetectionsAnprRoute: typeof DetectionsAnprRoute
  DetectionsFaceRoute: typeof DetectionsFaceRoute
  DetectionsHumanRoute: typeof DetectionsHumanRoute
  DetectionsVehicleRoute: typeof DetectionsVehicleRoute
  IncidentsIdRoute: typeof IncidentsIdRoute
  SurveillancePriorityRoute: typeof SurveillancePriorityRoute
  TrackingJourneyRoute: typeof TrackingJourneyRoute
  TrackingPersonRoute: typeof TrackingPersonRoute
  TrackingVehicleRoute: typeof TrackingVehicleRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
  SurveillanceIndexRoute: typeof SurveillanceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera-health': {
      id: '/camera-health'
      path: '/camera-health'
      fullPath: '/camera-health'
      preLoaderRoute: typeof CameraHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fences': {
      id: '/fences'
      path: '/fences'
      fullPath: '/fences'
      preLoaderRoute: typeof FencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigation': {
      id: '/investigation'
      path: '/investigation'
      fullPath: '/investigation'
      preLoaderRoute: typeof InvestigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cameras': {
      id: '/admin/cameras'
      path: '/admin/cameras'
      fullPath: '/admin/cameras'
      preLoaderRoute: typeof AdminCamerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/zones': {
      id: '/admin/zones'
      path: '/admin/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AdminZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detections/anpr': {
      id: '/detections/anpr'
      path: '/detections/anpr'
      fullPath: '/detections/anpr'
      preLoaderRoute: typeof DetectionsAnprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detections/face': {
      id: '/detections/face'
      path: '/detections/face'
      fullPath: '/detections/face'
      preLoaderRoute: typeof DetectionsFaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detections/human': {
      id: '/detections/human'
      path: '/detections/human'
      fullPath: '/detections/human'
      preLoaderRoute: typeof DetectionsHumanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detections/vehicle': {
      id: '/detections/vehicle'
      path: '/detections/vehicle'
      fullPath: '/detections/vehicle'
      preLoaderRoute: typeof DetectionsVehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/': {
      id: '/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof IncidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/$id': {
      id: '/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof IncidentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveillance/': {
      id: '/surveillance/'
      path: '/surveillance'
      fullPath: '/surveillance/'
      preLoaderRoute: typeof SurveillanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveillance/priority': {
      id: '/surveillance/priority'
      path: '/surveillance/priority'
      fullPath: '/surveillance/priority'
      preLoaderRoute: typeof SurveillancePriorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/journey': {
      id: '/tracking/journey'
      path: '/tracking/journey'
      fullPath: '/tracking/journey'
      preLoaderRoute: typeof TrackingJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/person': {
      id: '/tracking/person'
      path: '/tracking/person'
      fullPath: '/tracking/person'
      preLoaderRoute: typeof TrackingPersonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/vehicle': {
      id: '/tracking/vehicle'
      path: '/tracking/vehicle'
      fullPath: '/tracking/vehicle'
      preLoaderRoute: typeof TrackingVehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  CameraHealthRoute: CameraHealthRoute,
  DashboardRoute: DashboardRoute,
  EvidenceRoute: EvidenceRoute,
  FencesRoute: FencesRoute,
  InvestigationRoute: InvestigationRoute,
  JourneyRoute: JourneyRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  ReportsRoute: ReportsRoute,
  RiskRoute: RiskRoute,
  SearchRoute: SearchRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCamerasRoute: AdminCamerasRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminZonesRoute: AdminZonesRoute,
  DetectionsAnprRoute: DetectionsAnprRoute,
  DetectionsFaceRoute: DetectionsFaceRoute,
  DetectionsHumanRoute: DetectionsHumanRoute,
  DetectionsVehicleRoute: DetectionsVehicleRoute,
  IncidentsIdRoute: IncidentsIdRoute,
  SurveillancePriorityRoute: SurveillancePriorityRoute,
  TrackingJourneyRoute: TrackingJourneyRoute,
  TrackingPersonRoute: TrackingPersonRoute,
  TrackingVehicleRoute: TrackingVehicleRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
  SurveillanceIndexRoute: SurveillanceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
